# Generated by Django 5.1.7 on 2025-04-20 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ae9d0196-b920-4fd2-94cb-3b8f7dca7ce1'), primary_key=True, serialize=False)),
                ('method', models.TextField(choices=[('Dinheiro', 'Money'), ('A vista', 'A Vista'), ('Credito', 'Credito'), ('PIX', 'Pix')])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.TextField(choices=[('Aguardando Pagamento', 'Awaiting Payment'), ('Concluido', 'Concluded'), ('Cancelado', 'Canceled')])),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.rent')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
