# Generated by Django 5.1.7 on 2025-04-20 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_id_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ae9d0196-b920-4fd2-94cb-3b8f7dca7ce1'), primary_key=True, serialize=False)),
                ('rent_start', models.DateTimeField()),
                ('rent_end', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.TextField(choices=[('Aguardando Pagamento', 'Awaiting Payment'), ('Em Andamento', 'On Going'), ('Entregue', 'Delivered'), ('Cancelado', 'Canceled')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
