# Generated by Django 5.1.7 on 2025-04-20 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('64a773bb-b8d7-4a36-bad7-652769107d85'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('isbn', models.CharField(max_length=15)),
                ('category', models.TextField(choices=[('Romance', 'Romance'), ('Drama', 'Drama')], max_length=15)),
                ('writter', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cover', models.ImageField(upload_to='./book/media/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
