# Generated by Django 5.1.7 on 2025-04-20 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae9d0196-b920-4fd2-94cb-3b8f7dca7ce1'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ae9d0196-b920-4fd2-94cb-3b8f7dca7ce1'), primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
